apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ .Release.Name }}-letsncrypt
  labels: 
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ template "external-k8s-forwarding.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  acme:
    email: {{ .Values.acme.email }}
    server: {{ .Values.acme.server }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsncrypt
    dns01:
      providers:
      - name: cloudflare
        cloudflare:
          email: {{ .Values.cloudflare.email }}
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: apikey.txt
