apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:  
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ template "external-k8s-forwarding.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    kubernetes.io/ingress.class: traefik
  name: {{ .Release.Name }}
spec:
  tls:
  - secretName: {{ .Release.Name }}-tls
    hosts:
    - '*.{{ .Values.domain }}'
  rules:
    - host: myapp.{{ .Values.domain }}
      http:
        paths:
          - backend:
              serviceName: myapp
              servicePort: 3000
            path: /
    - host: myapp2.{{ .Values.domain }}
      http:
        paths:
          - backend:
              serviceName: myapp
              servicePort: 3000
            path: /